export const presetPrograms = {
  workouts: [
    {
      name: "10-Minute Abs & Core Blast",
      duration_minutes: 10,
      focus: "Abs / Cardio",
      intensity: "High",
      sets_per_round: 2,
      rest_between_exercises_seconds: 15,
      notes:
        "Perform 2 sets of the circuit. Minimize rest to keep intensity high.",
      exercises: [
        {
          name: "Mountain Climber",
          duration_seconds: 45,
          target_muscles: ["cardiovascular system", "core", "shoulders"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/RJgzwny.gif",
        },
        {
          name: "Cable Squatting Curl",
          duration_seconds: 45,
          target_musplements: ["biceps", "forearms"],
          equipment: ["cable"],
          gifUrl: "https://static.exercisedb.dev/media/3XFdb1Z.gif",
        },
        {
          name: "Push-up Plus",
          duration_seconds: 45,
          target_muscles: ["pectorals", "triceps", "shoulders"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/pvBMLHA.gif",
        },
        {
          name: "Bear Crawl",
          duration_seconds: 45,
          target_muscles: ["cardiovascular system", "core", "shoulders"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/0Yz8WdV.gif",
        },
        {
          name: "Flutter Kicks",
          duration_seconds: 45,
          target_muscles: ["glutes", "hip flexors", "lower abs"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/UVo2Qs2.gif",
        },
      ],
    },
    {
      name: "10-Minute Upper Back & Biceps",
      duration_minutes: 10,
      focus: "Back / Arms",
      intensity: "Moderate",
      sets_per_round: 2,
      rest_between_exercises_seconds: 15,
      notes:
        "Perform 2 sets of the circuit, focusing on a strong squeeze in the back muscles.",
      exercises: [
        {
          name: "Inverted Row",
          duration_seconds: 45,
          target_muscles: ["upper back", "biceps", "forearms"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/bZGHsAZ.gif",
        },
        {
          name: "Dumbbell Standing Biceps Curl",
          duration_seconds: 45,
          target_muscles: ["biceps", "forearms"],
          equipment: ["dumbbell"],
          gifUrl: "https://static.exercisedb.dev/media/3s4NnTh.gif",
        },
        {
          name: "Bodyweight Standing Close-Grip Row",
          duration_seconds: 45,
          target_muscles: ["upper back", "biceps", "forearms"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/tig3PXb.gif",
        },
        {
          name: "Dumbbell Hammer Curl V. 2",
          duration_seconds: 45,
          target_muscles: ["biceps", "forearms"],
          equipment: ["dumbbell"],
          gifUrl: "https://static.exercisedb.dev/media/2NpxjC1.gif",
        },
        {
          name: "Inverted Row Bent Knees",
          duration_seconds: 45,
          target_muscles: ["upper back", "biceps", "forearms"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/VPPtusI.gif",
        },
      ],
    },
    {
      name: "15-Minute Glute & Quad Sculpt",
      duration_minutes: 15,
      focus: "Lower Body",
      intensity: "Moderate-High",
      sets_per_round: 3,
      rest_between_exercises_seconds: 15,
      notes:
        "Perform 3 sets of the circuit. Drive through your heels on all lifting movements.",
      exercises: [
        {
          name: "Kettlebell Goblet Squat",
          duration_seconds: 45,
          target_muscles: ["glutes", "quadriceps", "hamstrings"],
          equipment: ["kettlebell"],
          gifUrl: "https://static.exercisedb.dev/media/ZA8b5hc.gif",
        },
        {
          name: "Barbell Full Squat (Back Pov)",
          duration_seconds: 45,
          target_muscles: ["glutes", "quadriceps", "hamstrings", "core"],
          equipment: ["barbell"],
          gifUrl: "https://static.exercisedb.dev/media/DhMl549.gif",
        },
        {
          name: "Dumbbell Step-Up",
          duration_seconds: 45,
          target_muscles: ["glutes", "quadriceps", "hamstrings"],
          equipment: ["dumbbell"],
          gifUrl: "https://static.exercisedb.dev/media/aXtJhlg.gif",
        },
        {
          name: "Barbell Rear Lunge V. 2",
          duration_seconds: 45,
          target_muscles: ["glutes", "quadriceps", "hamstrings"],
          equipment: ["barbell"],
          gifUrl: "https://static.exercisedb.dev/media/62Nw60O.gif",
        },
        {
          name: "Jump Squat",
          duration_seconds: 45,
          target_muscles: ["glutes", "quadriceps", "hamstrings"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/LIlE5Tn.gif",
        },
      ],
    },
    {
      name: "15-Minute Shoulder & Tricep Builder",
      duration_minutes: 15,
      focus: "Shoulders / Triceps",
      intensity: "Moderate",
      sets_per_round: 3,
      rest_between_exercises_seconds: 15,
      notes:
        "Perform 3 sets of the circuit. Control the weight and avoid swinging.",
      exercises: [
        {
          name: "Dumbbell Standing Overhead Press",
          duration_seconds: 45,
          target_muscles: ["delts", "triceps", "upper back"],
          equipment: ["dumbbell"],
          gifUrl: "https://static.exercisedb.dev/media/A6wtbuL.gif",
        },
        {
          name: "Cable Pushdown (with Rope Attachment)",
          duration_seconds: 45,
          target_muscles: ["triceps", "forearms"],
          equipment: ["cable"],
          gifUrl: "https://static.exercisedb.dev/media/dU605di.gif",
        },
        {
          name: "Dumbbell Lateral Raise",
          duration_seconds: 45,
          target_muscles: ["delts", "traps"],
          equipment: ["dumbbell"],
          gifUrl: "https://static.exercisedb.dev/media/DsgkuIt.gif",
        },
        {
          name: "Bench Dip (Knees Bent)",
          duration_seconds: 45,
          target_muscles: ["triceps", "chest", "shoulders"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/RrLske5.gif",
        },
        {
          name: "Dumbbell Rear Lateral Raise",
          duration_seconds: 45,
          target_muscles: ["delts", "traps", "rhomboids"],
          equipment: ["dumbbell"],
          gifUrl: "https://static.exercisedb.dev/media/v1qBec9.gif",
        },
      ],
    },
    {
      name: "30-Minute Intense Ab Workout",
      duration_minutes: 30,
      focus: "Abs / Core",
      intensity: "Very High",
      sets_per_round: 4,
      rest_between_supersets_seconds: 60,
      notes:
        "This routine uses supersets. Rest only 60 seconds after completing a round of both Superset A & B.",
      supersets: [
        {
          name: "Superset 1: Core Strength",
          exercises: [
            {
              name: "Dumbbell Side Plank with Rear Fly",
              duration_seconds: 45,
              target_muscles: ["upper back", "shoulders", "core"],
              equipment: ["dumbbell"],
              side_focus: "Alternating / Per Side",
              gifUrl: "https://static.exercisedb.dev/media/X6ytgYZ.gif",
            },
            {
              name: "Weighted Hyperextension (on Stability Ball)",
              duration_seconds: 45,
              target_muscles: ["spine", "glutes", "hamstrings"],
              equipment: ["weighted"],
              gifUrl: "https://static.exercisedb.dev/media/8urJS9b.gif",
            },
          ],
        },
        {
          name: "Superset 2: Lower Abs & Obliques",
          exercises: [
            {
              name: "Twist Hip Lift",
              duration_seconds: 45,
              target_muscles: ["glutes", "obliques", "hamstrings"],
              equipment: ["body weight"],
              side_focus: "Alternating",
              gifUrl: "https://static.exercisedb.dev/media/AX1kB0o.gif",
            },
            {
              name: "Push-up on Lower Arms",
              duration_seconds: 45,
              target_muscles: ["triceps", "chest", "shoulders"],
              equipment: ["body weight"],
              gifUrl: "https://static.exercisedb.dev/media/4Jt8QsQ.gif",
            },
          ],
        },
        {
          name: "Superset 3: Rotational Power",
          exercises: [
            {
              name: "Cable Twisting Pull",
              duration_seconds: 45,
              target_muscles: ["lats", "shoulders", "biceps"],
              equipment: ["cable"],
              side_focus: "Alternating / Per Side",
              gifUrl: "https://static.exercisedb.dev/media/zCgxPbV.gif",
            },
            {
              name: "Barbell Press Sit-Up",
              duration_seconds: 45,
              target_muscles: ["abs", "shoulders", "chest"],
              equipment: ["barbell"],
              gifUrl: "https://static.exercisedb.dev/media/wnEscH8.gif",
            },
          ],
        },
        {
          name: "Superset 4: Trunk & Stability",
          exercises: [
            {
              name: "Kettlebell Alternating Renegade Row",
              duration_seconds: 45,
              target_muscles: ["upper back", "core", "shoulders"],
              equipment: ["kettlebell"],
              gifUrl: "https://static.exercisedb.dev/media/b9kqlBy.gif",
            },
            {
              name: "Mountain Climber",
              duration_seconds: 45,
              target_muscles: ["cardiovascular system", "core", "shoulders"],
              equipment: ["body weight"],
              gifUrl: "https://static.exercisedb.dev/media/RJgzwny.gif",
            },
          ],
        },
      ],
    },
  ],
};
