export const presetPrograms = {
  workouts: [
    {
      name: "10-Minute Bodyweight Burn",
      duration_minutes: 10,
      focus: "Full Body / Cardio",
      intensity: "High",
      sets_per_round: 2,
      rest_between_exercises_seconds: 15,
      notes:
        "Fast-paced, full-body circuit designed for max calorie burn. Perform 2 rounds of all exercises.",
      mustHaveEquipment: ["body weight"],
      exercises: [
        {
          name: "Star Jump (Male)",
          duration_seconds: 45,
          target_muscles: [
            "cardiovascular system",
            "quadriceps",
            "hamstrings",
            "calves",
          ],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/HtfCpfi.gif",
          exerciseId: "HtfCpfi",
        },
        {
          name: "Jump Squat",
          duration_seconds: 45,
          target_muscles: ["glutes", "quadriceps", "hamstrings", "calves"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/LIlE5Tn.gif",
          exerciseId: "LIlE5Tn",
        },
        {
          name: "Mountain Climber",
          duration_seconds: 45,
          target_muscles: [
            "cardiovascular system",
            "core",
            "shoulders",
            "triceps",
          ],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/RJgzwny.gif",
          exerciseId: "RJgzwny",
        },
        {
          name: "Forward Jump",
          duration_seconds: 45,
          target_muscles: ["quadriceps", "calves", "hamstrings", "glutes"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/uZKq7lo.gif",
          exerciseId: "uZKq7lo",
        },
        {
          name: "Lunge with Jump",
          duration_seconds: 45,
          target_muscles: ["glutes", "quadriceps", "hamstrings", "calves"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/PM1PZjg.gif",
          exerciseId: "PM1PZjg",
        },
      ],
    },
    {
      name: "10-Minute Bodyweight Abs",
      duration_minutes: 10,
      focus: "Core Isolation",
      intensity: "High",
      sets_per_round: 2,
      rest_between_exercises_seconds: 15,
      notes:
        "No equipment needed. Focus on slow, controlled contractions for maximum core engagement. Perform 2 rounds.",
      mustHaveEquipment: ["body weight"],
      exercises: [
        {
          name: "Flutter Kicks",
          duration_seconds: 45,
          target_muscles: ["glutes", "hip flexors", "lower abs"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/UVo2Qs2.gif",
          exerciseId: "UVo2Qs2",
        },
        {
          name: "Diamond Push-up",
          duration_seconds: 45,
          target_muscles: ["triceps", "chest", "shoulders"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/soIB2rj.gif",
          exerciseId: "soIB2rj",
        },
        {
          name: "Scapula Push-up",
          duration_seconds: 45,
          target_muscles: ["serratus anterior", "triceps", "shoulders"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/jV65tKx.gif",
          exerciseId: "jV65tKx",
        },
        {
          name: "Bent Knee Lying Twist (Male)",
          duration_seconds: 45,
          target_muscles: ["glutes", "obliques", "hip flexors"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/6sYyrRX.gif",
          exerciseId: "6sYyrRX",
        },
        {
          name: "Push-up Plus",
          duration_seconds: 45,
          target_muscles: ["pectorals", "triceps", "shoulders"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/pvBMLHA.gif",
          exerciseId: "pvBMLHA",
        },
      ],
    },
    {
      name: "10-Minute Abs & Core Blast",
      duration_minutes: 10,
      focus: "Abs / Cardio",
      intensity: "High",
      sets_per_round: 2,
      rest_between_exercises_seconds: 15,
      notes:
        "Perform 2 sets of the circuit. Minimize rest to keep intensity high.",
      mustHaveEquipment: ["Dumbbell", "Cable"],
      exercises: [
        {
          name: "Mountain Climber",
          duration_seconds: 45,
          target_muscles: ["cardiovascular system", "core", "shoulders"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/RJgzwny.gif",
          exerciseId: "RJgzwny",
        },
        {
          name: "Cable Squatting Curl",
          duration_seconds: 45,
          target_muscles: ["biceps", "forearms"],
          equipment: ["cable"],
          gifUrl: "https://static.exercisedb.dev/media/3XFdb1Z.gif",
          exerciseId: "3XFdb1Z",
        },
        {
          name: "Push-up Plus",
          duration_seconds: 45,
          target_muscles: ["pectorals", "triceps", "shoulders"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/pvBMLHA.gif",
          exerciseId: "pvBMLHA",
        },
        {
          name: "Bear Crawl",
          duration_seconds: 45,
          target_muscles: ["cardiovascular system", "core", "shoulders"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/0Yz8WdV.gif",
          exerciseId: "0Yz8WdV",
        },
        {
          name: "Flutter Kicks",
          duration_seconds: 45,
          target_muscles: ["glutes", "hip flexors", "lower abs"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/UVo2Qs2.gif",
          exerciseId: "UVo2Qs2",
        },
      ],
    },
    {
      name: "10-Minute Upper Back & Biceps",
      duration_minutes: 10,
      focus: "Back / Arms",
      intensity: "Moderate",
      sets_per_round: 2,
      rest_between_exercises_seconds: 15,
      notes:
        "Perform 2 sets of the circuit, focusing on a strong squeeze in the back muscles.",
      mustHaveEquipment: ["Dumbbell"],
      exercises: [
        {
          name: "Inverted Row",
          duration_seconds: 45,
          target_muscles: ["upper back", "biceps", "forearms"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/bZGHsAZ.gif",
          exerciseId: "bZGHsAZ",
        },
        {
          name: "Dumbbell Standing Biceps Curl",
          duration_seconds: 45,
          target_muscles: ["biceps", "forearms"],
          equipment: ["dumbbell"],
          gifUrl: "https://static.exercisedb.dev/media/3s4NnTh.gif",
          exerciseId: "3s4NnTh",
        },
        {
          name: "Bodyweight Standing Close-Grip Row",
          duration_seconds: 45,
          target_muscles: ["upper back", "biceps", "forearms"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/tig3PXb.gif",
          exerciseId: "tig3PXb",
        },
        {
          name: "Dumbbell Hammer Curl V. 2",
          duration_seconds: 45,
          target_muscles: ["biceps", "forearms"],
          equipment: ["dumbbell"],
          gifUrl: "https://static.exercisedb.dev/media/2NpxjC1.gif",
          exerciseId: "2NpxjC1",
        },
        {
          name: "Inverted Row Bent Knees",
          duration_seconds: 45,
          target_muscles: ["upper back", "biceps", "forearms"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/VPPtusI.gif",
          exerciseId: "VPPtusI",
        },
      ],
    },
    {
      name: "15-Minute Glute & Quad Sculpt",
      duration_minutes: 15,
      focus: "Lower Body",
      intensity: "Moderate-High",
      sets_per_round: 3,
      rest_between_exercises_seconds: 15,
      notes:
        "Perform 3 sets of the circuit. Drive through your heels on all lifting movements.",
      mustHaveEquipment: ["Kettlebell", "Barbell", "Dumbbell"],
      exercises: [
        {
          name: "Kettlebell Goblet Squat",
          duration_seconds: 45,
          target_muscles: ["glutes", "quadriceps", "hamstrings"],
          equipment: ["kettlebell"],
          gifUrl: "https://static.exercisedb.dev/media/ZA8b5hc.gif",
          exerciseId: "ZA8b5hc",
        },
        {
          name: "Barbell Full Squat (Back Pov)",
          duration_seconds: 45,
          target_muscles: ["glutes", "quadriceps", "hamstrings", "core"],
          equipment: ["barbell"],
          gifUrl: "https://static.exercisedb.dev/media/DhMl549.gif",
          exerciseId: "DhMl549",
        },
        {
          name: "Dumbbell Step-Up",
          duration_seconds: 45,
          target_muscles: ["glutes", "quadriceps", "hamstrings"],
          equipment: ["dumbbell"],
          gifUrl: "https://static.exercisedb.dev/media/aXtJhlg.gif",
          exerciseId: "aXtJhlg",
        },
        {
          name: "Barbell Rear Lunge V. 2",
          duration_seconds: 45,
          target_muscles: ["glutes", "quadriceps", "hamstrings"],
          equipment: ["barbell"],
          gifUrl: "https://static.exercisedb.dev/media/62Nw60O.gif",
          exerciseId: "62Nw60O",
        },
        {
          name: "Jump Squat",
          duration_seconds: 45,
          target_muscles: ["glutes", "quadriceps", "hamstrings"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/LIlE5Tn.gif",
          exerciseId: "LIlE5Tn",
        },
      ],
    },
    {
      name: "15-Minute Shoulder & Tricep Builder",
      duration_minutes: 15,
      focus: "Shoulders / Triceps",
      intensity: "Moderate",
      sets_per_round: 3,
      rest_between_exercises_seconds: 15,
      notes:
        "Perform 3 sets of the circuit. Control the weight and avoid swinging.",
      mustHaveEquipment: ["Dumbbell", "Cable"],
      exercises: [
        {
          name: "Dumbbell Standing Overhead Press",
          duration_seconds: 45,
          target_muscles: ["delts", "triceps", "upper back"],
          equipment: ["dumbbell"],
          gifUrl: "https://static.exercisedb.dev/media/A6wtbuL.gif",
          exerciseId: "A6wtbuL",
        },
        {
          name: "Cable Pushdown (with Rope Attachment)",
          duration_seconds: 45,
          target_muscles: ["triceps", "forearms"],
          equipment: ["cable"],
          gifUrl: "https://static.exercisedb.dev/media/dU605di.gif",
          exerciseId: "dU605di",
        },
        {
          name: "Dumbbell Lateral Raise",
          duration_seconds: 45,
          target_muscles: ["delts", "traps"],
          equipment: ["dumbbell"],
          gifUrl: "https://static.exercisedb.dev/media/DsgkuIt.gif",
          exerciseId: "DsgkuIt",
        },
        {
          name: "Bench Dip (Knees Bent)",
          duration_seconds: 45,
          target_muscles: ["triceps", "chest", "shoulders"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/RrLske5.gif",
          exerciseId: "RrLske5",
        },
        {
          name: "Dumbbell Rear Lateral Raise",
          duration_seconds: 45,
          target_muscles: ["delts", "traps", "rhomboids"],
          equipment: ["dumbbell"],
          gifUrl: "https://static.exercisedb.dev/media/v1qBec9.gif",
          exerciseId: "v1qBec9",
        },
      ],
    },
    {
      name: "30-Minute Intense Ab Workout",
      duration_minutes: 30,
      focus: "Abs / Core",
      intensity: "Very High",
      sets_per_round: 4,
      rest_between_exercises_seconds: 15,
      notes:
        "Perform 4 total rounds. Rest 60 seconds after completing a full cycle of exercises.",
      mustHaveEquipment: ["Dumbbell", "Kettlebell", "Cable", "Barbell"],
      exercises: [
        {
          name: "Dumbbell Side Plank with Rear Fly",
          duration_seconds: 45,
          target_muscles: ["upper back", "shoulders", "core"],
          equipment: ["dumbbell"],
          gifUrl: "https://static.exercisedb.dev/media/X6ytgYZ.gif",
          exerciseId: "X6ytgYZ",
        },
        {
          name: "Weighted Hyperextension (on Stability Ball)",
          duration_seconds: 45,
          target_muscles: ["spine", "glutes", "hamstrings"],
          equipment: ["weighted"],
          gifUrl: "https://static.exercisedb.dev/media/8urJS9b.gif",
          exerciseId: "8urJS9b",
        },
        {
          name: "Twist Hip Lift",
          duration_seconds: 45,
          target_muscles: ["glutes", "obliques", "hamstrings"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/AX1kB0o.gif",
          exerciseId: "AX1kB0o",
        },
        {
          name: "Push-up on Lower Arms",
          duration_seconds: 45,
          target_muscles: ["triceps", "chest", "shoulders"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/4Jt8QsQ.gif",
          exerciseId: "4Jt8QsQ",
        },
        {
          name: "Cable Twisting Pull",
          duration_seconds: 45,
          target_muscles: ["lats", "shoulders", "biceps"],
          equipment: ["cable"],
          gifUrl: "https://static.exercisedb.dev/media/zCgxPbV.gif",
          exerciseId: "zCgxPbV",
        },
        {
          name: "Barbell Press Sit-Up",
          duration_seconds: 45,
          target_muscles: ["abs", "shoulders", "chest"],
          equipment: ["barbell"],
          gifUrl: "https://static.exercisedb.dev/media/wnEscH8.gif",
          exerciseId: "wnEscH8",
        },
        {
          name: "Kettlebell Alternating Renegade Row",
          duration_seconds: 45,
          target_muscles: ["upper back", "core", "shoulders"],
          equipment: ["kettlebell"],
          gifUrl: "https://static.exercisedb.dev/media/b9kqlBy.gif",
          exerciseId: "b9kqlBy",
        },
        {
          name: "Mountain Climber",
          duration_seconds: 45,
          target_muscles: ["cardiovascular system", "core", "shoulders"],
          equipment: ["body weight"],
          gifUrl: "https://static.exercisedb.dev/media/RJgzwny.gif",
          exerciseId: "RJgzwny",
        },
      ],
    },
  ],
};
