export const PresetPlans = [
  {
    beginner: {
      weightLoss: {
        week1: {
          day1: [
            {
              name: "triceps dip (between benches)",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/Wgbn9qo.gif",
              exerciseId: "Wgbn9qo",
            },
            {
              name: "bodyweight kneeling triceps extension",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/s0HKO2I.gif",
              exerciseId: "s0HKO2I",
            },
            {
              name: "close-grip push-up (on knees)",
              sets: 3,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/v3vLFW0.gif",
              exerciseId: "v3vLFW0",
            },
          ],
          day2: [
            {
              name: "triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/uOV3Itw.gif",
              exerciseId: "uOV3Itw",
            },
            {
              name: "elbow dips",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/LkoAWAE.gif",
              exerciseId: "LkoAWAE",
            },
            {
              name: "back lever",
              sets: 3,
              reps: 5,
              gif: "https://static.exercisedb.dev/media/GaSzzuh.gif",
              exerciseId: "GaSzzuh",
            },
          ],
          day3: [
            {
              name: "upper back stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/GSDioYu.gif",
              exerciseId: "GSDioYu",
            },
            {
              name: "bodyweight standing close-grip row",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/tig3PXb.gif",
              exerciseId: "tig3PXb",
            },
            {
              name: "inverted row with straps",
              sets: 3,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/jdiExfW.gif",
              exerciseId: "jdiExfW",
            },
          ],
          day4: [
            {
              name: "medicine ball overhead slam",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/oHg8eop.gif",
              exerciseId: "oHg8eop",
            },
            {
              name: "triceps dip (between benches)",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/Wgbn9qo.gif",
              exerciseId: "Wgbn9qo",
            },
            {
              name: "triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/uOV3Itw.gif",
              exerciseId: "uOV3Itw",
            },
          ],
          day5: [
            {
              name: "suspended row",
              sets: 3,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/4OaumBr.gif",
              exerciseId: "4OaumBr",
            },
            {
              name: "elbow dips",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/LkoAWAE.gif",
              exerciseId: "LkoAWAE",
            },
            {
              name: "overhead triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/Z5YStHW.gif",
              exerciseId: "Z5YStHW",
            },
          ],
          day6: [
            {
              name: "close-grip push-up (on knees)",
              sets: 3,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/v3vLFW0.gif",
              exerciseId: "v3vLFW0",
            },
            {
              name: "bodyweight standing one arm row (with towel)",
              sets: 3,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/O4oIqQD.gif",
              exerciseId: "O4oIqQD",
            },
            {
              name: "inverted row on bench",
              sets: 3,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/Mxa7Cr8.gif",
              exerciseId: "Mxa7Cr8",
            },
          ],
          day7: [
            {
              name: "upper back stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/GSDioYu.gif",
              exerciseId: "GSDioYu",
            },
            {
              name: "overhead triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/Z5YStHW.gif",
              exerciseId: "Z5YStHW",
            },
            {
              name: "bodyweight kneeling triceps extension",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/s0HKO2I.gif",
              exerciseId: "s0HKO2I",
            },
          ],
        },
        week2: {
          day1: [
            {
              name: "bodyweight standing close-grip one arm row",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/v2DfH14.gif",
              exerciseId: "v2DfH14",
            },
            {
              name: "triceps dip (between benches)",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/Wgbn9qo.gif",
              exerciseId: "Wgbn9qo",
            },
            {
              name: "medicine ball overhead slam",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/oHg8eop.gif",
              exerciseId: "oHg8eop",
            },
          ],
          day2: [
            {
              name: "inverted row on bench",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/Mxa7Cr8.gif",
              exerciseId: "Mxa7Cr8",
            },
            {
              name: "elbow lift - reverse push-up",
              sets: 3,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/wbUYILZ.gif",
              exerciseId: "wbUYILZ",
            },
            {
              name: "triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/uOV3Itw.gif",
              exerciseId: "uOV3Itw",
            },
          ],
          day3: [
            {
              name: "suspended row",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/4OaumBr.gif",
              exerciseId: "4OaumBr",
            },
            {
              name: "close-grip push-up (on knees)",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/v3vLFW0.gif",
              exerciseId: "v3vLFW0",
            },
            {
              name: "bodyweight standing close-grip row",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/tig3PXb.gif",
              exerciseId: "tig3PXb",
            },
          ],
          day4: [
            {
              name: "triceps dip (between benches)",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/Wgbn9qo.gif",
              exerciseId: "Wgbn9qo",
            },
            {
              name: "medicine ball overhead slam",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/oHg8eop.gif",
              exerciseId: "oHg8eop",
            },
            {
              name: "overhead triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/Z5YStHW.gif",
              exerciseId: "Z5YStHW",
            },
          ],
          day5: [
            {
              name: "inverted row with straps",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/jdiExfW.gif",
              exerciseId: "jdiExfW",
            },
            {
              name: "bodyweight kneeling triceps extension",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/s0HKO2I.gif",
              exerciseId: "s0HKO2I",
            },
            {
              name: "elbow dips",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/LkoAWAE.gif",
              exerciseId: "LkoAWAE",
            },
          ],
          day6: [
            {
              name: "bodyweight standing close-grip one arm row",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/v2DfH14.gif",
              exerciseId: "v2DfH14",
            },
            {
              name: "close-grip push-up (on knees)",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/v3vLFW0.gif",
              exerciseId: "v3vLFW0",
            },
            {
              name: "back lever",
              sets: 3,
              reps: 6,
              gif: "https://static.exercisedb.dev/media/GaSzzuh.gif",
              exerciseId: "GaSzzuh",
            },
          ],
          day7: [
            {
              name: "upper back stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/GSDioYu.gif",
              exerciseId: "GSDioYu",
            },
            {
              name: "elbow lift - reverse push-up",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/wbUYILZ.gif",
              exerciseId: "wbUYILZ",
            },
            {
              name: "triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/uOV3Itw.gif",
              exerciseId: "uOV3Itw",
            },
          ],
        },
      },
      muscleGain: {
        week1: {
          day1: [
            {
              name: "lever one arm lateral high row",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/OIFMAp1.gif",
              exerciseId: "OIFMAp1",
            },
            {
              name: "barbell pendlay row",
              sets: 3,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/r0z6xzQ.gif",
              exerciseId: "r0z6xzQ",
            },
            {
              name: "dumbbell reverse grip incline bench one arm row",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/ZIViNh1.gif",
              exerciseId: "ZIViNh1",
            },
          ],
          day2: [
            {
              name: "ez-bar close-grip bench press",
              sets: 3,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/da4cXST.gif",
              exerciseId: "da4cXST",
            },
            {
              name: "cable seated row",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/fUBheHs.gif",
              exerciseId: "fUBheHs",
            },
            {
              name: "dumbbell tricep kickback with stork stance",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/wOLmCXc.gif",
              exerciseId: "wOLmCXc",
            },
          ],
          day3: [
            {
              name: "lever bent-over row with v-bar",
              sets: 3,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/LuBEORI.gif",
              exerciseId: "LuBEORI",
            },
            {
              name: "cable seated wide-grip row",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/qcY50ZD.gif",
              exerciseId: "qcY50ZD",
            },
            {
              name: "dumbbell incline y-raise",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/PbzNu7c.gif",
              exerciseId: "PbzNu7c",
            },
          ],
          day4: [
            {
              name: "weighted tricep dips",
              sets: 3,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/bZq4bwK.gif",
              exerciseId: "bZq4bwK",
            },
            {
              name: "cable rope extension incline bench row",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/MgKwAAo.gif",
              exerciseId: "MgKwAAo",
            },
            {
              name: "cable standing row (v-bar)",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/4f8RXP8.gif",
              exerciseId: "4f8RXP8",
            },
          ],
          day5: [
            {
              name: "lever seated row",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/7I6LNUG.gif",
              exerciseId: "7I6LNUG",
            },
            {
              name: "dumbbell lying one arm supinated triceps extension",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/zZlORz6.gif",
              exerciseId: "zZlORz6",
            },
            {
              name: "dumbbell close-grip press",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/RxayqAZ.gif",
              exerciseId: "RxayqAZ",
            },
          ],
          day6: [
            {
              name: "cable decline seated wide-grip row",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/kesXOpB.gif",
              exerciseId: "kesXOpB",
            },
            {
              name: "cable rope high pulley overhead tricep extension",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/NN8nSNT.gif",
              exerciseId: "NN8nSNT",
            },
            {
              name: "barbell one arm bent over row",
              sets: 3,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/Jsgsc27.gif",
              exerciseId: "Jsgsc27",
            },
          ],
          day7: [
            {
              name: "cable seated one arm alternate row",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/vpp9Ku2.gif",
              exerciseId: "vpp9Ku2",
            },
            {
              name: "lever narrow grip seated row - strength variation",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/iCPqbki.gif",
              exerciseId: "iCPqbki",
            },
            {
              name: "dumbbell seated bench extension",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/JhYSVwT.gif",
              exerciseId: "JhYSVwT",
            },
          ],
        },
        week2: {
          day1: [
            {
              name: "dumbbell reverse grip incline bench one arm row",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/ZIViNh1.gif",
              exerciseId: "ZIViNh1",
            },
            {
              name: "ez-bar close-grip bench press",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/da4cXST.gif",
              exerciseId: "da4cXST",
            },
            {
              name: "cable one arm tricep pushdown",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/qRZ5S1N.gif",
              exerciseId: "qRZ5S1N",
            },
          ],
          day2: [
            {
              name: "lever bent-over row with v-bar",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/LuBEORI.gif",
              exerciseId: "LuBEORI",
            },
            {
              name: "cable seated wide-grip row",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/qcY50ZD.gif",
              exerciseId: "qcY50ZD",
            },
            {
              name: "dumbbell incline hammer press on exercise ball",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/wkgnGfb.gif",
              exerciseId: "wkgnGfb",
            },
          ],
          day3: [
            {
              name: "weighted tricep dips",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/bZq4bwK.gif",
              exerciseId: "bZq4bwK",
            },
            {
              name: "cable rope extension incline bench row",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/MgKwAAo.gif",
              exerciseId: "MgKwAAo",
            },
            {
              name: "lever narrow grip seated row - strength variation",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/iCPqbki.gif",
              exerciseId: "iCPqbki",
            },
          ],
          day4: [
            {
              name: "barbell one arm bent over row",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/Jsgsc27.gif",
              exerciseId: "Jsgsc27",
            },
            {
              name: "cable seated one arm alternate row",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/vpp9Ku2.gif",
              exerciseId: "vpp9Ku2",
            },
            {
              name: "dumbbell lying one arm supinated triceps extension",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/zZlORz6.gif",
              exerciseId: "zZlORz6",
            },
          ],
          day5: [
            {
              name: "cable seated row",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/fUBheHs.gif",
              exerciseId: "fUBheHs",
            },
            {
              name: "cable decline seated wide-grip row",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/kesXOpB.gif",
              exerciseId: "kesXOpB",
            },
            {
              name: "cable rope high pulley overhead tricep extension",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/NN8nSNT.gif",
              exerciseId: "NN8nSNT",
            },
          ],
          day6: [
            {
              name: "dumbbell close-grip press",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/RxayqAZ.gif",
              exerciseId: "RxayqAZ",
            },
            {
              name: "lever seated row",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/7I6LNUG.gif",
              exerciseId: "7I6LNUG",
            },
            {
              name: "dumbbell incline y-raise",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/PbzNu7c.gif",
              exerciseId: "PbzNu7c",
            },
          ],
          day7: [
            {
              name: "lever one arm lateral high row",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/OIFMAp1.gif",
              exerciseId: "OIFMAp1",
            },
            {
              name: "barbell pendlay row",
              sets: 3,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/r0z6xzQ.gif",
              exerciseId: "r0z6xzQ",
            },
            {
              name: "cable one arm bent over row",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/EIsE3u8.gif",
              exerciseId: "EIsE3u8",
            },
          ],
        },
      },
      endurance: {
        week1: {
          day1: [
            {
              name: "rope climb",
              sets: 3,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/yaAxcQr.gif",
              exerciseId: "yaAxcQr",
            },
            {
              name: "skin the cat",
              sets: 3,
              reps: 5,
              gif: "https://static.exercisedb.dev/media/MSfvriJ.gif",
              exerciseId: "MSfvriJ",
            },
            {
              name: "bodyweight standing close-grip one arm row",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/v2DfH14.gif",
              exerciseId: "v2DfH14",
            },
          ],
          day2: [
            {
              name: "medicine ball overhead slam",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/oHg8eop.gif",
              exerciseId: "oHg8eop",
            },
            {
              name: "triceps dip (between benches)",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/Wgbn9qo.gif",
              exerciseId: "Wgbn9qo",
            },
            {
              name: "elbow dips",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/LkoAWAE.gif",
              exerciseId: "LkoAWAE",
            },
          ],
          day3: [
            {
              name: "bodyweight kneeling triceps extension",
              sets: 3,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/s0HKO2I.gif",
              exerciseId: "s0HKO2I",
            },
            {
              name: "close-grip push-up (on knees)",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/v3vLFW0.gif",
              exerciseId: "v3vLFW0",
            },
            {
              name: "inverted row on bench",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/Mxa7Cr8.gif",
              exerciseId: "Mxa7Cr8",
            },
          ],
          day4: [
            {
              name: "triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/uOV3Itw.gif",
              exerciseId: "uOV3Itw",
            },
            {
              name: "suspended row",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/4OaumBr.gif",
              exerciseId: "4OaumBr",
            },
            {
              name: "bodyweight standing one arm row (with towel)",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/O4oIqQD.gif",
              exerciseId: "O4oIqQD",
            },
          ],
          day5: [
            {
              name: "medicine ball overhead slam",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/oHg8eop.gif",
              exerciseId: "oHg8eop",
            },
            {
              name: "elbow lift - reverse push-up",
              sets: 3,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/wbUYILZ.gif",
              exerciseId: "wbUYILZ",
            },
            {
              name: "triceps dip (between benches)",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/Wgbn9qo.gif",
              exerciseId: "Wgbn9qo",
            },
          ],
          day6: [
            {
              name: "skin the cat",
              sets: 3,
              reps: 6,
              gif: "https://static.exercisedb.dev/media/MSfvriJ.gif",
              exerciseId: "MSfvriJ",
            },
            {
              name: "rope climb",
              sets: 3,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/yaAxcQr.gif",
              exerciseId: "yaAxcQr",
            },
            {
              name: "bodyweight standing close-grip row",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/tig3PXb.gif",
              exerciseId: "tig3PXb",
            },
          ],
          day7: [
            {
              name: "upper back stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/GSDioYu.gif",
              exerciseId: "GSDioYu",
            },
            {
              name: "overhead triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/Z5YStHW.gif",
              exerciseId: "Z5YStHW",
            },
            {
              name: "elbow dips",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/LkoAWAE.gif",
              exerciseId: "LkoAWAE",
            },
          ],
        },
        week2: {
          day1: [
            {
              name: "bodyweight kneeling triceps extension",
              sets: 3,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/s0HKO2I.gif",
              exerciseId: "s0HKO2I",
            },
            {
              name: "close-grip push-up (on knees)",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/v3vLFW0.gif",
              exerciseId: "v3vLFW0",
            },
            {
              name: "inverted row with straps",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/jdiExfW.gif",
              exerciseId: "jdiExfW",
            },
          ],
          day2: [
            {
              name: "medicine ball overhead slam",
              sets: 3,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/oHg8eop.gif",
              exerciseId: "oHg8eop",
            },
            {
              name: "suspended row",
              sets: 3,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/4OaumBr.gif",
              exerciseId: "4OaumBr",
            },
            {
              name: "back lever",
              sets: 3,
              reps: 7,
              gif: "https://static.exercisedb.dev/media/GaSzzuh.gif",
              exerciseId: "GaSzzuh",
            },
          ],
          day3: [
            {
              name: "elbow lift - reverse push-up",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/wbUYILZ.gif",
              exerciseId: "wbUYILZ",
            },
            {
              name: "bodyweight standing close-grip one arm row",
              sets: 3,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/v2DfH14.gif",
              exerciseId: "v2DfH14",
            },
            {
              name: "triceps dip (between benches)",
              sets: 3,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/Wgbn9qo.gif",
              exerciseId: "Wgbn9qo",
            },
          ],
          day4: [
            {
              name: "inverted row on bench",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/Mxa7Cr8.gif",
              exerciseId: "Mxa7Cr8",
            },
            {
              name: "medicine ball overhead slam",
              sets: 3,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/oHg8eop.gif",
              exerciseId: "oHg8eop",
            },
            {
              name: "elbow dips",
              sets: 3,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/LkoAWAE.gif",
              exerciseId: "LkoAWAE",
            },
          ],
          day5: [
            {
              name: "bodyweight kneeling triceps extension",
              sets: 3,
              reps: 22,
              gif: "https://static.exercisedb.dev/media/s0HKO2I.gif",
              exerciseId: "s0HKO2I",
            },
            {
              name: "bodyweight standing one arm row (with towel)",
              sets: 3,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/O4oIqQD.gif",
              exerciseId: "O4oIqQD",
            },
            {
              name: "triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/uOV3Itw.gif",
              exerciseId: "uOV3Itw",
            },
          ],
          day6: [
            {
              name: "close-grip push-up (on knees)",
              sets: 3,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/v3vLFW0.gif",
              exerciseId: "v3vLFW0",
            },
            {
              name: "inverted row with straps",
              sets: 3,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/jdiExfW.gif",
              exerciseId: "jdiExfW",
            },
            {
              name: "skin the cat",
              sets: 3,
              reps: 7,
              gif: "https://static.exercisedb.dev/media/MSfvriJ.gif",
              exerciseId: "MSfvriJ",
            },
          ],
          day7: [
            {
              name: "upper back stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/GSDioYu.gif",
              exerciseId: "GSDioYu",
            },
            {
              name: "overhead triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/Z5YStHW.gif",
              exerciseId: "Z5YStHW",
            },
            {
              name: "rope climb",
              sets: 3,
              reps: "45 sec",
              gif: "https://static.exercisedb.dev/media/yaAxcQr.gif",
              exerciseId: "yaAxcQr",
            },
          ],
        },
      },
    },
    intermediate: {
      weightLoss: {
        week1: {
          day1: [
            {
              name: "cable seated row",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/fUBheHs.gif",
              exerciseId: "fUBheHs",
            },
            {
              name: "cable one arm bent over row",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/EIsE3u8.gif",
              exerciseId: "EIsE3u8",
            },
            {
              name: "dumbbell twisting bench press",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/z6TAHoT.gif",
              exerciseId: "z6TAHoT",
            },
            {
              name: "cable rope extension incline bench row",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/MgKwAAo.gif",
              exerciseId: "MgKwAAo",
            },
          ],
          day2: [
            {
              name: "lever bent-over row with v-bar",
              sets: 4,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/LuBEORI.gif",
              exerciseId: "LuBEORI",
            },
            {
              name: "barbell pin presses",
              sets: 4,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/bndCa3Q.gif",
              exerciseId: "bndCa3Q",
            },
            {
              name: "lever seated row",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/7I6LNUG.gif",
              exerciseId: "7I6LNUG",
            },
            {
              name: "cable alternate triceps extension",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/Gchi5Tr.gif",
              exerciseId: "Gchi5Tr",
            },
          ],
          day3: [
            {
              name: "dumbbell incline y-raise",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/PbzNu7c.gif",
              exerciseId: "PbzNu7c",
            },
            {
              name: "cable rope lying on floor tricep extension",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/U3ffHlY.gif",
              exerciseId: "U3ffHlY",
            },
            {
              name: "cable seated wide-grip row",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/qcY50ZD.gif",
              exerciseId: "qcY50ZD",
            },
            {
              name: "dumbbell lying extension (across face)",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/L2V5Nan.gif",
              exerciseId: "L2V5Nan",
            },
          ],
          day4: [
            {
              name: "assisted triceps dip (kneeling)",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/J60bN17.gif",
              exerciseId: "J60bN17",
            },
            {
              name: "cable floor seated wide-grip row",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/veXwo0D.gif",
              exerciseId: "veXwo0D",
            },
            {
              name: "cable upper row",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/PQStVXH.gif",
              exerciseId: "PQStVXH",
            },
            {
              name: "cable reverse-grip pushdown",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/VjYliFZ.gif",
              exerciseId: "VjYliFZ",
            },
          ],
          day5: [
            {
              name: "lever narrow grip seated row - strength variation",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/iCPqbki.gif",
              exerciseId: "iCPqbki",
            },
            {
              name: "barbell decline close grip to skull press",
              sets: 4,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/LMGXZn8.gif",
              exerciseId: "LMGXZn8",
            },
            {
              name: "dumbbell kickbacks on exercise ball",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/cAvTaSg.gif",
              exerciseId: "cAvTaSg",
            },
            {
              name: "cable decline seated wide-grip row",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/kesXOpB.gif",
              exerciseId: "kesXOpB",
            },
          ],
          day6: [
            {
              name: "cable standing reverse grip one arm overhead tricep extension",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/i11JWU7.gif",
              exerciseId: "i11JWU7",
            },
            {
              name: "barbell one arm bent over row",
              sets: 4,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/Jsgsc27.gif",
              exerciseId: "Jsgsc27",
            },
            {
              name: "cable overhead triceps extension (rope attachment)",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/2IxROQ1.gif",
              exerciseId: "2IxROQ1",
            },
            {
              name: "cable rope high pulley overhead tricep extension",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/NN8nSNT.gif",
              exerciseId: "NN8nSNT",
            },
          ],
          day7: [
            {
              name: "lever one arm lateral high row",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/OIFMAp1.gif",
              exerciseId: "OIFMAp1",
            },
            {
              name: "cable seated one arm alternate row",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/vpp9Ku2.gif",
              exerciseId: "vpp9Ku2",
            },
            {
              name: "barbell pendlay row",
              sets: 4,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/r0z6xzQ.gif",
              exerciseId: "r0z6xzQ",
            },
            {
              name: "dumbbell incline hammer press on exercise ball",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/wkgnGfb.gif",
              exerciseId: "wkgnGfb",
            },
          ],
        },
        week2: {
          day1: [
            {
              name: "cable seated row",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/fUBheHs.gif",
              exerciseId: "fUBheHs",
            },
            {
              name: "cable one arm tricep pushdown",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/qRZ5S1N.gif",
              exerciseId: "qRZ5S1N",
            },
            {
              name: "cable rope extension incline bench row",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/MgKwAAo.gif",
              exerciseId: "MgKwAAo",
            },
            {
              name: "cable seated wide-grip row",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/qcY50ZD.gif",
              exerciseId: "qcY50ZD",
            },
          ],
          day2: [
            {
              name: "lever bent-over row with v-bar",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/LuBEORI.gif",
              exerciseId: "LuBEORI",
            },
            {
              name: "barbell pin presses",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/bndCa3Q.gif",
              exerciseId: "bndCa3Q",
            },
            {
              name: "lever seated row",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/7I6LNUG.gif",
              exerciseId: "7I6LNUG",
            },
            {
              name: "cable standing row (v-bar)",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/4f8RXP8.gif",
              exerciseId: "4f8RXP8",
            },
          ],
          day3: [
            {
              name: "dumbbell incline y-raise",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/PbzNu7c.gif",
              exerciseId: "PbzNu7c",
            },
            {
              name: "cable rope lying on floor tricep extension",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/U3ffHlY.gif",
              exerciseId: "U3ffHlY",
            },
            {
              name: "cable upper row",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/PQStVXH.gif",
              exerciseId: "PQStVXH",
            },
            {
              name: "dumbbell lying extension (across face)",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/L2V5Nan.gif",
              exerciseId: "L2V5Nan",
            },
          ],
          day4: [
            {
              name: "assisted triceps dip (kneeling)",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/J60bN17.gif",
              exerciseId: "J60bN17",
            },
            {
              name: "cable floor seated wide-grip row",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/veXwo0D.gif",
              exerciseId: "veXwo0D",
            },
            {
              name: "cable reverse-grip pushdown",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/VjYliFZ.gif",
              exerciseId: "VjYliFZ",
            },
            {
              name: "lever narrow grip seated row - strength variation",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/iCPqbki.gif",
              exerciseId: "iCPqbki",
            },
          ],
          day5: [
            {
              name: "barbell decline close grip to skull press",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/LMGXZn8.gif",
              exerciseId: "LMGXZn8",
            },
            {
              name: "dumbbell kickbacks on exercise ball",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/cAvTaSg.gif",
              exerciseId: "cAvTaSg",
            },
            {
              name: "cable decline seated wide-grip row",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/kesXOpB.gif",
              exerciseId: "kesXOpB",
            },
            {
              name: "cable overhead triceps extension (rope attachment)",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/2IxROQ1.gif",
              exerciseId: "2IxROQ1",
            },
          ],
          day6: [
            {
              name: "cable rope high pulley overhead tricep extension",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/NN8nSNT.gif",
              exerciseId: "NN8nSNT",
            },
            {
              name: "barbell one arm bent over row",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/Jsgsc27.gif",
              exerciseId: "Jsgsc27",
            },
            {
              name: "cable seated one arm alternate row",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/vpp9Ku2.gif",
              exerciseId: "vpp9Ku2",
            },
            {
              name: "lever one arm lateral high row",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/OIFMAp1.gif",
              exerciseId: "OIFMAp1",
            },
          ],
          day7: [
            {
              name: "barbell pendlay row",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/r0z6xzQ.gif",
              exerciseId: "r0z6xzQ",
            },
            {
              name: "dumbbell incline hammer press on exercise ball",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/wkgnGfb.gif",
              exerciseId: "wkgnGfb",
            },
            {
              name: "cable standing reverse grip one arm overhead tricep extension",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/i11JWU7.gif",
              exerciseId: "i11JWU7",
            },
            {
              name: "dumbbell twisting bench press",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/z6TAHoT.gif",
              exerciseId: "z6TAHoT",
            },
          ],
        },
      },
      endurance: {
        week1: {
          day1: [
            {
              name: "rope climb",
              sets: 4,
              reps: "45 sec",
              gif: "https://static.exercisedb.dev/media/yaAxcQr.gif",
              exerciseId: "yaAxcQr",
            },
            {
              name: "skin the cat",
              sets: 4,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/MSfvriJ.gif",
              exerciseId: "MSfvriJ",
            },
            {
              name: "extended style inverted row",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/1YUWDNZ.gif",
              exerciseId: "1YUWDNZ",
            },
            {
              name: "incline close-grip push-up",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/1YB40kg.gif",
              exerciseId: "1YB40kg",
            },
          ],
          day2: [
            {
              name: "medicine ball overhead slam",
              sets: 4,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/oHg8eop.gif",
              exerciseId: "oHg8eop",
            },
            {
              name: "inverted row on bench",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/Mxa7Cr8.gif",
              exerciseId: "Mxa7Cr8",
            },
            {
              name: "close-grip push-up",
              sets: 4,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/x6KpKpq.gif",
              exerciseId: "x6KpKpq",
            },
            {
              name: "bodyweight kneeling triceps extension",
              sets: 4,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/s0HKO2I.gif",
              exerciseId: "s0HKO2I",
            },
          ],
          day3: [
            {
              name: "inverted row with straps",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/jdiExfW.gif",
              exerciseId: "jdiExfW",
            },
            {
              name: "assisted triceps dip (kneeling)",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/J60bN17.gif",
              exerciseId: "J60bN17",
            },
            {
              name: "elbow lift - reverse push-up",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/wbUYILZ.gif",
              exerciseId: "wbUYILZ",
            },
            {
              name: "triceps dip (between benches)",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/Wgbn9qo.gif",
              exerciseId: "Wgbn9qo",
            },
          ],
          day4: [
            {
              name: "bodyweight standing close-grip one arm row",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/v2DfH14.gif",
              exerciseId: "v2DfH14",
            },
            {
              name: "elbow dips",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/LkoAWAE.gif",
              exerciseId: "LkoAWAE",
            },
            {
              name: "bodyweight standing close-grip row",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/tig3PXb.gif",
              exerciseId: "tig3PXb",
            },
            {
              name: "bodyweight kneeling triceps extension",
              sets: 4,
              reps: 22,
              gif: "https://static.exercisedb.dev/media/s0HKO2I.gif",
              exerciseId: "s0HKO2I",
            },
          ],
          day5: [
            {
              name: "suspended row",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/4OaumBr.gif",
              exerciseId: "4OaumBr",
            },
            {
              name: "extended style inverted row",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/1YUWDNZ.gif",
              exerciseId: "1YUWDNZ",
            },
            {
              name: "close-grip push-up (on knees)",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/v3vLFW0.gif",
              exerciseId: "v3vLFW0",
            },
            {
              name: "triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/uOV3Itw.gif",
              exerciseId: "uOV3Itw",
            },
          ],
          day6: [
            {
              name: "rope climb",
              sets: 4,
              reps: "45 sec",
              gif: "https://static.exercisedb.dev/media/yaAxcQr.gif",
              exerciseId: "yaAxcQr",
            },
            {
              name: "skin the cat",
              sets: 4,
              reps: 9,
              gif: "https://static.exercisedb.dev/media/MSfvriJ.gif",
              exerciseId: "MSfvriJ",
            },
            {
              name: "inverted row on bench",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/Mxa7Cr8.gif",
              exerciseId: "Mxa7Cr8",
            },
            {
              name: "incline close-grip push-up",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/1YB40kg.gif",
              exerciseId: "1YB40kg",
            },
          ],
          day7: [
            {
              name: "overhead triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/Z5YStHW.gif",
              exerciseId: "Z5YStHW",
            },
            {
              name: "upper back stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/GSDioYu.gif",
              exerciseId: "GSDioYu",
            },
            {
              name: "medicine ball overhead slam",
              sets: 4,
              reps: 22,
              gif: "https://static.exercisedb.dev/media/oHg8eop.gif",
              exerciseId: "oHg8eop",
            },
          ],
        },
        week2: {
          day1: [
            {
              name: "extended style inverted row",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/1YUWDNZ.gif",
              exerciseId: "1YUWDNZ",
            },
            {
              name: "incline close-grip push-up",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/1YB40kg.gif",
              exerciseId: "1YB40kg",
            },
            {
              name: "close-grip push-up",
              sets: 4,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/x6KpKpq.gif",
              exerciseId: "x6KpKpq",
            },
            {
              name: "inverted row on bench",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/Mxa7Cr8.gif",
              exerciseId: "Mxa7Cr8",
            },
          ],
          day2: [
            {
              name: "bodyweight kneeling triceps extension",
              sets: 4,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/s0HKO2I.gif",
              exerciseId: "s0HKO2I",
            },
            {
              name: "bodyweight standing close-grip one arm row",
              sets: 4,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/v2DfH14.gif",
              exerciseId: "v2DfH14",
            },
            {
              name: "elbow lift - reverse push-up",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/wbUYILZ.gif",
              exerciseId: "wbUYILZ",
            },
            {
              name: "back lever",
              sets: 4,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/GaSzzuh.gif",
              exerciseId: "GaSzzuh",
            },
          ],
          day3: [
            {
              name: "medicine ball overhead slam",
              sets: 4,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/oHg8eop.gif",
              exerciseId: "oHg8eop",
            },
            {
              name: "suspended row",
              sets: 4,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/4OaumBr.gif",
              exerciseId: "4OaumBr",
            },
            {
              name: "close-grip push-up (on knees)",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/v3vLFW0.gif",
              exerciseId: "v3vLFW0",
            },
            {
              name: "inverted row with straps",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/jdiExfW.gif",
              exerciseId: "jdiExfW",
            },
          ],
          day4: [
            {
              name: "triceps dip (between benches)",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/Wgbn9qo.gif",
              exerciseId: "Wgbn9qo",
            },
            {
              name: "bodyweight standing one arm row (with towel)",
              sets: 4,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/O4oIqQD.gif",
              exerciseId: "O4oIqQD",
            },
            {
              name: "elbow dips",
              sets: 4,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/LkoAWAE.gif",
              exerciseId: "LkoAWAE",
            },
            {
              name: "triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/uOV3Itw.gif",
              exerciseId: "uOV3Itw",
            },
          ],
          day5: [
            {
              name: "rope climb",
              sets: 4,
              reps: "60 sec",
              gif: "https://static.exercisedb.dev/media/yaAxcQr.gif",
              exerciseId: "yaAxcQr",
            },
            {
              name: "skin the cat",
              sets: 4,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/MSfvriJ.gif",
              exerciseId: "MSfvriJ",
            },
            {
              name: "bodyweight standing close-grip row",
              sets: 4,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/tig3PXb.gif",
              exerciseId: "tig3PXb",
            },
            {
              name: "overhead triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/Z5YStHW.gif",
              exerciseId: "Z5YStHW",
            },
          ],
          day6: [
            {
              name: "incline close-grip push-up",
              sets: 4,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/1YB40kg.gif",
              exerciseId: "1YB40kg",
            },
            {
              name: "extended style inverted row",
              sets: 4,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/1YUWDNZ.gif",
              exerciseId: "1YUWDNZ",
            },
            {
              name: "close-grip push-up",
              sets: 4,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/x6KpKpq.gif",
              exerciseId: "x6KpKpq",
            },
            {
              name: "bodyweight kneeling triceps extension",
              sets: 4,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/s0HKO2I.gif",
              exerciseId: "s0HKO2I",
            },
          ],
          day7: [
            {
              name: "upper back stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/GSDioYu.gif",
              exerciseId: "GSDioYu",
            },
            {
              name: "inverted row on bench",
              sets: 4,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/Mxa7Cr8.gif",
              exerciseId: "Mxa7Cr8",
            },
            {
              name: "elbow lift - reverse push-up",
              sets: 4,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/wbUYILZ.gif",
              exerciseId: "wbUYILZ",
            },
            {
              name: "triceps dip (between benches)",
              sets: 4,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/Wgbn9qo.gif",
              exerciseId: "Wgbn9qo",
            },
          ],
        },
      },
    },
    advanced: {
      weightLoss: {
        week1: {
          day1: [
            {
              name: "lever one arm lateral high row",
              sets: 5,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/OIFMAp1.gif",
              exerciseId: "OIFMAp1",
            },
            {
              name: "ez barbell seated triceps extension",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/iaapw0g.gif",
              exerciseId: "iaapw0g",
            },
            {
              name: "barbell pendlay row",
              sets: 5,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/r0z6xzQ.gif",
              exerciseId: "r0z6xzQ",
            },
            {
              name: "dumbbell reverse grip incline bench one arm row",
              sets: 5,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/ZIViNh1.gif",
              exerciseId: "ZIViNh1",
            },
          ],
          day2: [
            {
              name: "smith close-grip bench press",
              sets: 5,
              reps: 8,
              gif: "https://static.exercisedb.dev/media/WcHl7ru.gif",
              exerciseId: "WcHl7ru",
            },
            {
              name: "cable seated row",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/fUBheHs.gif",
              exerciseId: "fUBheHs",
            },
            {
              name: "dumbbell tricep kickback with stork stance",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/wOLmCXc.gif",
              exerciseId: "wOLmCXc",
            },
            {
              name: "cable seated wide-grip row",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/qcY50ZD.gif",
              exerciseId: "qcY50ZD",
            },
          ],
          day3: [
            {
              name: "lever bent-over row with v-bar",
              sets: 5,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/LuBEORI.gif",
              exerciseId: "LuBEORI",
            },
            {
              name: "dumbbell incline y-raise",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/PbzNu7c.gif",
              exerciseId: "PbzNu7c",
            },
            {
              name: "cable rope lying on floor tricep extension",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/U3ffHlY.gif",
              exerciseId: "U3ffHlY",
            },
            {
              name: "weighted tricep dips",
              sets: 5,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/bZq4bwK.gif",
              exerciseId: "bZq4bwK",
            },
          ],
          day4: [
            {
              name: "cable rope extension incline bench row",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/MgKwAAo.gif",
              exerciseId: "MgKwAAo",
            },
            {
              name: "cable standing row (v-bar)",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/4f8RXP8.gif",
              exerciseId: "4f8RXP8",
            },
            {
              name: "cable decline seated wide-grip row",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/kesXOpB.gif",
              exerciseId: "kesXOpB",
            },
            {
              name: "barbell one arm floor press",
              sets: 5,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/vtusOWT.gif",
              exerciseId: "vtusOWT",
            },
          ],
          day5: [
            {
              name: "lever narrow grip seated row - strength variation",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/iCPqbki.gif",
              exerciseId: "iCPqbki",
            },
            {
              name: "barbell decline close grip to skull press",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/LMGXZn8.gif",
              exerciseId: "LMGXZn8",
            },
            {
              name: "cable seated one arm alternate row",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/vpp9Ku2.gif",
              exerciseId: "vpp9Ku2",
            },
            {
              name: "cable high row (kneeling)",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/ZSJNetl.gif",
              exerciseId: "ZSJNetl",
            },
          ],
          day6: [
            {
              name: "cable standing reverse grip one arm overhead tricep extension",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/i11JWU7.gif",
              exerciseId: "i11JWU7",
            },
            {
              name: "barbell one arm bent over row",
              sets: 5,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/Jsgsc27.gif",
              exerciseId: "Jsgsc27",
            },
            {
              name: "cable overhead triceps extension (rope attachment)",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/2IxROQ1.gif",
              exerciseId: "2IxROQ1",
            },
            {
              name: "cable rope high pulley overhead tricep extension",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/NN8nSNT.gif",
              exerciseId: "NN8nSNT",
            },
          ],
          day7: [
            {
              name: "lever seated row",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/7I6LNUG.gif",
              exerciseId: "7I6LNUG",
            },
            {
              name: "dumbbell lying one arm supinated triceps extension",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/zZlORz6.gif",
              exerciseId: "zZlORz6",
            },
            {
              name: "dumbbell close-grip press",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/RxayqAZ.gif",
              exerciseId: "RxayqAZ",
            },
            {
              name: "lever bent-over row with v-bar",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/LuBEORI.gif",
              exerciseId: "LuBEORI",
            },
          ],
        },
        week2: {
          day1: [
            {
              name: "dumbbell reverse grip incline bench one arm row",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/ZIViNh1.gif",
              exerciseId: "ZIViNh1",
            },
            {
              name: "ez barbell seated triceps extension",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/iaapw0g.gif",
              exerciseId: "iaapw0g",
            },
            {
              name: "cable one arm tricep pushdown",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/qRZ5S1N.gif",
              exerciseId: "qRZ5S1N",
            },
            {
              name: "lever one arm lateral high row",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/OIFMAp1.gif",
              exerciseId: "OIFMAp1",
            },
          ],
          day2: [
            {
              name: "smith close-grip bench press",
              sets: 5,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/WcHl7ru.gif",
              exerciseId: "WcHl7ru",
            },
            {
              name: "cable seated wide-grip row",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/qcY50ZD.gif",
              exerciseId: "qcY50ZD",
            },
            {
              name: "dumbbell tricep kickback with stork stance",
              sets: 5,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/wOLmCXc.gif",
              exerciseId: "wOLmCXc",
            },
            {
              name: "barbell one arm bent over row",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/Jsgsc27.gif",
              exerciseId: "Jsgsc27",
            },
          ],
          day3: [
            {
              name: "lever bent-over row with v-bar",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/LuBEORI.gif",
              exerciseId: "LuBEORI",
            },
            {
              name: "dumbbell incline y-raise",
              sets: 5,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/PbzNu7c.gif",
              exerciseId: "PbzNu7c",
            },
            {
              name: "cable rope lying on floor tricep extension",
              sets: 5,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/U3ffHlY.gif",
              exerciseId: "U3ffHlY",
            },
            {
              name: "weighted tricep dips",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/bZq4bwK.gif",
              exerciseId: "bZq4bwK",
            },
          ],
          day4: [
            {
              name: "cable rope extension incline bench row",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/MgKwAAo.gif",
              exerciseId: "MgKwAAo",
            },
            {
              name: "cable standing row (v-bar)",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/4f8RXP8.gif",
              exerciseId: "4f8RXP8",
            },
            {
              name: "cable decline seated wide-grip row",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/kesXOpB.gif",
              exerciseId: "kesXOpB",
            },
            {
              name: "barbell one arm floor press",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/vtusOWT.gif",
              exerciseId: "vtusOWT",
            },
          ],
          day5: [
            {
              name: "lever narrow grip seated row - strength variation",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/iCPqbki.gif",
              exerciseId: "iCPqbki",
            },
            {
              name: "barbell decline close grip to skull press",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/LMGXZn8.gif",
              exerciseId: "LMGXZn8",
            },
            {
              name: "cable seated one arm alternate row",
              sets: 5,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/vpp9Ku2.gif",
              exerciseId: "vpp9Ku2",
            },
            {
              name: "cable high row (kneeling)",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/ZSJNetl.gif",
              exerciseId: "ZSJNetl",
            },
          ],
          day6: [
            {
              name: "cable standing reverse grip one arm overhead tricep extension",
              sets: 5,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/i11JWU7.gif",
              exerciseId: "i11JWU7",
            },
            {
              name: "barbell one arm bent over row",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/Jsgsc27.gif",
              exerciseId: "Jsgsc27",
            },
            {
              name: "cable overhead triceps extension (rope attachment)",
              sets: 5,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/2IxROQ1.gif",
              exerciseId: "2IxROQ1",
            },
            {
              name: "cable rope high pulley overhead tricep extension",
              sets: 5,
              reps: 18,
              gif: "https://static.exercisedb.dev/media/NN8nSNT.gif",
              exerciseId: "NN8nSNT",
            },
          ],
          day7: [
            {
              name: "lever seated row",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/7I6LNUG.gif",
              exerciseId: "7I6LNUG",
            },
            {
              name: "dumbbell lying one arm supinated triceps extension",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/zZlORz6.gif",
              exerciseId: "zZlORz6",
            },
            {
              name: "dumbbell close-grip press",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/RxayqAZ.gif",
              exerciseId: "RxayqAZ",
            },
            {
              name: "lever bent-over row with v-bar",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/LuBEORI.gif",
              exerciseId: "LuBEORI",
            },
          ],
        },
      },
      endurance: {
        week1: {
          day1: [
            {
              name: "rope climb",
              sets: 5,
              reps: "60 sec",
              gif: "https://static.exercisedb.dev/media/yaAxcQr.gif",
              exerciseId: "yaAxcQr",
            },
            {
              name: "skin the cat",
              sets: 5,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/MSfvriJ.gif",
              exerciseId: "MSfvriJ",
            },
            {
              name: "extended style inverted row",
              sets: 5,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/1YUWDNZ.gif",
              exerciseId: "1YUWDNZ",
            },
            {
              name: "incline close-grip push-up",
              sets: 5,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/1YB40kg.gif",
              exerciseId: "1YB40kg",
            },
          ],
          day2: [
            {
              name: "medicine ball overhead slam",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/oHg8eop.gif",
              exerciseId: "oHg8eop",
            },
            {
              name: "inverted row on bench",
              sets: 5,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/Mxa7Cr8.gif",
              exerciseId: "Mxa7Cr8",
            },
            {
              name: "close-grip push-up",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/x6KpKpq.gif",
              exerciseId: "x6KpKpq",
            },
            {
              name: "bodyweight kneeling triceps extension",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/s0HKO2I.gif",
              exerciseId: "s0HKO2I",
            },
          ],
          day3: [
            {
              name: "inverted row with straps",
              sets: 5,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/jdiExfW.gif",
              exerciseId: "jdiExfW",
            },
            {
              name: "assisted triceps dip (kneeling)",
              sets: 5,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/J60bN17.gif",
              exerciseId: "J60bN17",
            },
            {
              name: "elbow lift - reverse push-up",
              sets: 5,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/wbUYILZ.gif",
              exerciseId: "wbUYILZ",
            },
            {
              name: "triceps dip (between benches)",
              sets: 5,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/Wgbn9qo.gif",
              exerciseId: "Wgbn9qo",
            },
          ],
          day4: [
            {
              name: "bodyweight standing close-grip one arm row",
              sets: 5,
              reps: 22,
              gif: "https://static.exercisedb.dev/media/v2DfH14.gif",
              exerciseId: "v2DfH14",
            },
            {
              name: "elbow dips",
              sets: 5,
              reps: 22,
              gif: "https://static.exercisedb.dev/media/LkoAWAE.gif",
              exerciseId: "LkoAWAE",
            },
            {
              name: "bodyweight standing close-grip row",
              sets: 5,
              reps: 22,
              gif: "https://static.exercisedb.dev/media/tig3PXb.gif",
              exerciseId: "tig3PXb",
            },
            {
              name: "bodyweight kneeling triceps extension",
              sets: 5,
              reps: 28,
              gif: "https://static.exercisedb.dev/media/s0HKO2I.gif",
              exerciseId: "s0HKO2I",
            },
          ],
          day5: [
            {
              name: "suspended row",
              sets: 5,
              reps: 22,
              gif: "https://static.exercisedb.dev/media/4OaumBr.gif",
              exerciseId: "4OaumBr",
            },
            {
              name: "extended style inverted row",
              sets: 5,
              reps: 22,
              gif: "https://static.exercisedb.dev/media/1YUWDNZ.gif",
              exerciseId: "1YUWDNZ",
            },
            {
              name: "close-grip push-up (on knees)",
              sets: 5,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/v3vLFW0.gif",
              exerciseId: "v3vLFW0",
            },
            {
              name: "triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/uOV3Itw.gif",
              exerciseId: "uOV3Itw",
            },
          ],
          day6: [
            {
              name: "rope climb",
              sets: 5,
              reps: "60 sec",
              gif: "https://static.exercisedb.dev/media/yaAxcQr.gif",
              exerciseId: "yaAxcQr",
            },
            {
              name: "skin the cat",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/MSfvriJ.gif",
              exerciseId: "MSfvriJ",
            },
            {
              name: "inverted row on bench",
              sets: 5,
              reps: 22,
              gif: "https://static.exercisedb.dev/media/Mxa7Cr8.gif",
              exerciseId: "Mxa7Cr8",
            },
            {
              name: "incline close-grip push-up",
              sets: 5,
              reps: 22,
              gif: "https://static.exercisedb.dev/media/1YB40kg.gif",
              exerciseId: "1YB40kg",
            },
          ],
          day7: [
            {
              name: "overhead triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/Z5YStHW.gif",
              exerciseId: "Z5YStHW",
            },
            {
              name: "upper back stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/GSDioYu.gif",
              exerciseId: "GSDioYu",
            },
            {
              name: "medicine ball overhead slam",
              sets: 5,
              reps: 28,
              gif: "https://static.exercisedb.dev/media/oHg8eop.gif",
              exerciseId: "oHg8eop",
            },
            {
              name: "front lever reps",
              sets: 5,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/hbY9wqG.gif",
              exerciseId: "hbY9wqG",
            },
          ],
        },
        week2: {
          day1: [
            {
              name: "extended style inverted row",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/1YUWDNZ.gif",
              exerciseId: "1YUWDNZ",
            },
            {
              name: "incline close-grip push-up",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/1YB40kg.gif",
              exerciseId: "1YB40kg",
            },
            {
              name: "close-grip push-up",
              sets: 5,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/x6KpKpq.gif",
              exerciseId: "x6KpKpq",
            },
            {
              name: "inverted row on bench",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/Mxa7Cr8.gif",
              exerciseId: "Mxa7Cr8",
            },
          ],
          day2: [
            {
              name: "bodyweight kneeling triceps extension",
              sets: 5,
              reps: 30,
              gif: "https://static.exercisedb.dev/media/s0HKO2I.gif",
              exerciseId: "s0HKO2I",
            },
            {
              name: "bodyweight standing close-grip one arm row",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/v2DfH14.gif",
              exerciseId: "v2DfH14",
            },
            {
              name: "elbow lift - reverse push-up",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/wbUYILZ.gif",
              exerciseId: "wbUYILZ",
            },
            {
              name: "back lever",
              sets: 5,
              reps: 10,
              gif: "https://static.exercisedb.dev/media/GaSzzuh.gif",
              exerciseId: "GaSzzuh",
            },
          ],
          day3: [
            {
              name: "medicine ball overhead slam",
              sets: 5,
              reps: 30,
              gif: "https://static.exercisedb.dev/media/oHg8eop.gif",
              exerciseId: "oHg8eop",
            },
            {
              name: "suspended row",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/4OaumBr.gif",
              exerciseId: "4OaumBr",
            },
            {
              name: "close-grip push-up (on knees)",
              sets: 5,
              reps: 22,
              gif: "https://static.exercisedb.dev/media/v3vLFW0.gif",
              exerciseId: "v3vLFW0",
            },
            {
              name: "inverted row with straps",
              sets: 5,
              reps: 22,
              gif: "https://static.exercisedb.dev/media/jdiExfW.gif",
              exerciseId: "jdiExfW",
            },
          ],
          day4: [
            {
              name: "triceps dip (between benches)",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/Wgbn9qo.gif",
              exerciseId: "Wgbn9qo",
            },
            {
              name: "bodyweight standing one arm row (with towel)",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/O4oIqQD.gif",
              exerciseId: "O4oIqQD",
            },
            {
              name: "elbow dips",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/LkoAWAE.gif",
              exerciseId: "LkoAWAE",
            },
            {
              name: "triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/uOV3Itw.gif",
              exerciseId: "uOV3Itw",
            },
          ],
          day5: [
            {
              name: "rope climb",
              sets: 5,
              reps: "60 sec",
              gif: "https://static.exercisedb.dev/media/yaAxcQr.gif",
              exerciseId: "yaAxcQr",
            },
            {
              name: "skin the cat",
              sets: 5,
              reps: 15,
              gif: "https://static.exercisedb.dev/media/MSfvriJ.gif",
              exerciseId: "MSfvriJ",
            },
            {
              name: "bodyweight standing close-grip row",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/tig3PXb.gif",
              exerciseId: "tig3PXb",
            },
            {
              name: "overhead triceps stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/Z5YStHW.gif",
              exerciseId: "Z5YStHW",
            },
          ],
          day6: [
            {
              name: "incline close-grip push-up",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/1YB40kg.gif",
              exerciseId: "1YB40kg",
            },
            {
              name: "extended style inverted row",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/1YUWDNZ.gif",
              exerciseId: "1YUWDNZ",
            },
            {
              name: "close-grip push-up",
              sets: 5,
              reps: 20,
              gif: "https://static.exercisedb.dev/media/x6KpKpq.gif",
              exerciseId: "x6KpKpq",
            },
            {
              name: "bodyweight kneeling triceps extension",
              sets: 5,
              reps: 30,
              gif: "https://static.exercisedb.dev/media/s0HKO2I.gif",
              exerciseId: "s0HKO2I",
            },
          ],
          day7: [
            {
              name: "upper back stretch",
              sets: 2,
              reps: "30 sec",
              gif: "https://static.exercisedb.dev/media/GSDioYu.gif",
              exerciseId: "GSDioYu",
            },
            {
              name: "inverted row on bench",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/Mxa7Cr8.gif",
              exerciseId: "Mxa7Cr8",
            },
            {
              name: "elbow lift - reverse push-up",
              sets: 5,
              reps: 25,
              gif: "https://static.exercisedb.dev/media/wbUYILZ.gif",
              exerciseId: "wbUYILZ",
            },
            {
              name: "front lever reps",
              sets: 5,
              reps: 12,
              gif: "https://static.exercisedb.dev/media/hbY9wqG.gif",
              exerciseId: "hbY9wqG",
            },
          ],
        },
      },
    },
  },
];

export const filterPlanByDays = (plan, days) => {
  const filteredPlan = {};
  Object.keys(plan).forEach((week) => {
    const allDays = Object.keys(plan[week]);
    const selectedDays = allDays.slice(0, days);
    filteredPlan[week] = {};
    selectedDays.forEach((day) => {
      filteredPlan[week][day] = plan[week][day];
    });
  });
  return filteredPlan;
};
